### ISSUE TITLE
What's this for?

### ISSUE THREAD

**Issue by tobiasmuehl** [palindrom615/sdkman#5]
A client for the client? Is this an effort to provide Go bindings? This is the only package available through the [AUR](https://aur.archlinux.org/packages/sdkman/), but I don't understand why it exists. Original SDKMAN is just bash, curl, and unzip, this one is using Go

**Comment by palindrom615** [comment]
This is alternative of original SDKMAN client(yes, bash and curl). I originally made this because there was no windows support on original SDKMAN. And now I use this on linux and macOS because I don't like original sdkman downloads shell file from the internet and executes it. That is insecure any way.
